---
# Directories related tasks

- block:
    - name: Check required directories
      stat:
        path: "{{ config_directory_item }}"
      register: ansible_check_config_dir_result
      loop: >-
        {{ config_directories
           | reject("equalto", none)
           | reject("equalto", "")
           | list }}
      loop_control:
        loop_var: config_directory_item

    - name: Create required directories
      file:
        path: "{{ config_directory_item }}"
        state: directory
        mode: "{{ ansible_setup_directories_mode }}"
      when: >-
        not ansible_check_config_dir_result.results
            [config_directory_index].stat.exists
      loop: >-
        {{ config_directories
           | reject("equalto", none)
           | reject("equalto", "")
           | list }}
      loop_control:
        loop_var: config_directory_item
        index_var: config_directory_index
  vars:
    config_directories:
      - "{{ ansible_config_file_path | default('', true) | dirname }}"
      - "{{ ansible_defaults_inventory | default('', true) | dirname }}"
      - "{{ ansible_defaults_roles_path }}"
      - "{{ ansible_defaults_library }}"
      - "{{ ansible_defaults_module_utils }}"
      - "{{ ansible_defaults_remote_tmp }}"
      - "{{ ansible_defaults_local_tmp }}"

      - >-
        {{ ansible_defaults_plugin_filters_cfg
           | default('', true)
           | dirname }}

      - "{{ ansible_defaults_action_plugins }}"
      - "{{ ansible_defaults_cache_plugins }}"
      - "{{ ansible_defaults_callback_plugins }}"
      - "{{ ansible_defaults_connection_plugins }}"
      - "{{ ansible_defaults_lookup_plugins }}"
      - "{{ ansible_defaults_inventory_plugins }}"
      - "{{ ansible_defaults_vars_plugins }}"
      - "{{ ansible_defaults_filter_plugins }}"
      - "{{ ansible_defaults_test_plugins }}"
      - "{{ ansible_defaults_terminal_plugins }}"
      - "{{ ansible_defaults_strategy_plugins }}"
      - "{{ ansible_defaults_log_path | default('', true) | dirname }}"
  tags:
    - role::ansible
    - role::ansible::install
    - role::ansible::install::directories
