---
# Role install tasks

- block:
    - name: Install ansible
      include_role:
        name: amtega.packages
      vars:
        packages_os: "{{ ansible_packages_os }}"
        packages_python: "{{ ansible_packages_python }}"
      when:
        - ansible_required_version is defined
        - ansible_required_version is not none

    - name: Setup ansible directories
      include_tasks: directories.yaml
      when: ansible_setup_directories | bool

  environment:
    ANSIBLE_SKIP_CONFLICT_CHECK: >-
      {{ (ansible_skip_conflict_check | bool) | ternary("1", "0") }}
      
  tags:
    - role::ansible
    - role::ansible::install
