---
# Role install tasks

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop: >-
    {{ config_directories
       | reject("equalto", none)
       | reject("equalto", "")
       | list }}
  vars:
    config_directories:
      - >-
        {{ ansible_config_file | dirname
           if ansible_config_file is not none
           else none }}
      - >-
        {{ ansible_defaults_inventory | dirname
           if ansible_defaults_inventory is not none
           else none }}
      - "{{ ansible_defaults_roles_path }}"
      - "{{ ansible_defaults_library }}"
      - "{{ ansible_defaults_module_utils }}"
      - "{{ ansible_defaults_remote_tmp }}"
      - "{{ ansible_defaults_local_tmp }}"
      - >-
        {{ ansible_defaults_plugin_filters_cfg | dirname
           if ansible_defaults_plugin_filters_cfg is not none
           else none }}
      - "{{ ansible_defaults_action_plugins }}"
      - "{{ ansible_defaults_cache_plugins }}"
      - "{{ ansible_defaults_callback_plugins }}"
      - "{{ ansible_defaults_connection_plugins }}"
      - "{{ ansible_defaults_lookup_plugins }}"
      - "{{ ansible_defaults_inventory_plugins }}"
      - "{{ ansible_defaults_vars_plugins }}"
      - "{{ ansible_defaults_filter_plugins }}"
      - "{{ ansible_defaults_test_plugins }}"
      - "{{ ansible_defaults_terminal_plugins }}"
      - "{{ ansible_defaults_strategy_plugins }}"
      - "{{ ansible_defaults_log_path | dirname
            if ansible_defaults_log_path is not none
            else none }}"
  tags:
    - role::ansible
    - role::ansible::install
