# Role tasks

- name: Gather info
  import_tasks: gather.yml
  tags:
    - role::ansible

- name: Uninstall ansible
  import_tasks: uninstall.yml
  when: >-
    ansible_detected_major_version != ansible_required_major_version
    or ansible_detected_minor_version != ansible_required_minor_version
    or ansible_uninstall_first | bool
  tags:
    - role::ansible
    - role::ansible::uninstall

- name: Install ansible
  import_tasks: install.yml
  tags:
    - role::ansible
    - role::ansible::install

- name: Configure ansible
  import_tasks: configure.yml
  tags:
    - role::ansible
    - role::ansible::configure
