# Role tasks

- name: sanity checks
  import_tasks: check.yml
  tags:
    - role::ansible
    - role::ansible::check

- name: install ansible
  import_tasks: install.yml
  tags:
    - role::ansible
    - role::ansible::install

- name: configure ansible
  import_tasks: configure.yml
  tags:
    - role::ansible
    - role::ansible::configure
