# Role tasks

- name: Install ansible
  import_tasks: install.yml
  tags:
    - role::ansible
    - role::ansible::install

- name: Configure ansible
  import_tasks: configure.yml
  tags:
    - role::ansible
    - role::ansible::configure
