---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Get ansible version
      shell: >-
        set -o pipefail ; \
        /var/lib/ansible/venv/bin/pip show ansible | grep "Version:"
      changed_when: no
      register: ansible_version_result

    - name: Check that ansible version is correct
      assert:
        that: ansible_version_result.stdout_lines[0] is search("4.1.0")

    - name: Read ansible config file
      command: cat {{ ansible_config_file_path }}
      changed_when: no
      register: read_config_result

    - name: Verify config file content
      assert:
        that:
          - >-
            read_config_result.stdout
            is search("inventory = /etc/ansible/hosts")
          - >-
            read_config_result.stdout
            is search("roles_path = /etc/ansible/roles")
          - >-
            read_config_result.stdout
            is search("remote_tmp = /root/.ansible/tmp")
          - >-
            read_config_result.stdout
            is search("forks = 5")
          - >-
            read_config_result.stdout
            is search("enable_plugins = host_list, script, yaml, ini")

    - name: Search key file
      stat:
        path: "~/.ssh/id_rsa_ansible"
      register: check_key_result

    - name: Check key file exist
      assert:
        that:
          - check_key_result.stat.exists
